print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "D:/HUB_DES350/MAIN_FASTTRASH/NewLandfill_A4/Assets/Textile_Words/POLYESTER.mb"`)
{		
	file -o "D:/HUB_DES350/MAIN_FASTTRASH/NewLandfill_A4/Assets/Textile_Words/POLYESTER.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "D:/HUB_DES350/MAIN_FASTTRASH/NewLandfill_A4/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "D:/HUB_DES350/MAIN_FASTTRASH/NewLandfill_A4/Temp/CommandPipe";

$donepipeKill = `fopen "D:/HUB_DES350/MAIN_FASTTRASH/NewLandfill_A4/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
